<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Curia.Canon</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Curia.Canon.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Curia.Domain.Primitives/Curia.Domain.Primitives.csproj" />
  </ItemGroup>
</Project>
