<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="CsCheck" />
    <PackageReference Include="NSec.Cryptography" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Curia.Canon/Curia.Canon.csproj" />
    <ProjectReference Include="../../src/Curia.Canon.Sodium/Curia.Canon.Sodium.csproj" />
  </ItemGroup>
</Project>
