using System.Diagnostics.CodeAnalysis;
using Npgsql;
using Xunit;

namespace Curia.Infrastructure.Tests;

/// <summary>
/// db/0005's grant (R4.32, errata G14), proved the way <see cref="OperationalStateGrantTests"/> proves
/// 0002's: on a connection opened as the application role, asserting Postgres's own
/// insufficient-privilege state. Each column the role must not rewrite is its own row, so a failure
/// names the privilege that was granted; the two window columns are the positive control, so the
/// refusals are a narrow grant and not a role with no UPDATE at all.
/// </summary>
[Collection(PostgresCollectionDefinition.Name)]
[SuppressMessage(
    "Naming",
    "CA1707:Identifiers should not contain underscores",
    Justification = "Test names carry the requirement IDs they enforce verbatim.")]
public sealed class AgentKeyMaterialGrantTests
{
    private readonly PostgresDatabaseFixture _fixture;

    public AgentKeyMaterialGrantTests(PostgresDatabaseFixture fixture) => _fixture = fixture;

    /// <summary>
    /// Self-assignment, so the statement is well typed for every column and fails on privilege alone.
    /// Postgres checks column privileges before evaluating WHERE, so no row need exist.
    /// </summary>
    [SuppressMessage(
        "Security",
        "CA2100:Review SQL queries for security vulnerabilities",
        Justification = "The interpolated column name comes from this theory's own [InlineData] literals.")]
    [Theory]
    [InlineData("kid")]
    [InlineData("agent_id")]
    [InlineData("alg")]
    [InlineData("public_key")]
    public async Task R4_32_TheAppRoleCannotRewriteAKeysIdentityOrMaterial(string column)
    {
        var ct = TestContext.Current.CancellationToken;
        await using var connection = await _fixture.AppRoleDataSource.OpenConnectionAsync(ct);
        await using var command = new NpgsqlCommand(
            $"UPDATE agent_keys SET {column} = {column} WHERE kid = 'no-such-kid';", connection);

        var ex = await Assert.ThrowsAsync<PostgresException>(() => command.ExecuteNonQueryAsync(ct));
        Assert.Equal(PostgresErrorCodes.InsufficientPrivilege, ex.SqlState);
        Assert.Contains("permission denied for table agent_keys", ex.MessageText, StringComparison.Ordinal);
    }

    /// <summary>The positive control: the window is still the role's to move, which R4.19's revocation needs.</summary>
    [SuppressMessage(
        "Security",
        "CA2100:Review SQL queries for security vulnerabilities",
        Justification = "The interpolated column name comes from this theory's own [InlineData] literals.")]
    [Theory]
    [InlineData("valid_from")]
    [InlineData("valid_until")]
    public async Task R4_19_TheAppRoleCanStillMoveAKeysWindow(string column)
    {
        var ct = TestContext.Current.CancellationToken;
        await using var connection = await _fixture.AppRoleDataSource.OpenConnectionAsync(ct);
        await using var command = new NpgsqlCommand(
            $"UPDATE agent_keys SET {column} = {column} WHERE kid = 'no-such-kid';", connection);

        Assert.Equal(0, await command.ExecuteNonQueryAsync(ct));
    }

    /// <summary>R4.19's never-delete, in the one form 0002's REVOKE DELETE does not name.</summary>
    [Fact]
    public async Task R4_19_TheAppRoleCannotTruncateAgentKeys()
    {
        var ct = TestContext.Current.CancellationToken;
        await using var connection = await _fixture.AppRoleDataSource.OpenConnectionAsync(ct);
        await using var command = new NpgsqlCommand("TRUNCATE agent_keys;", connection);

        var ex = await Assert.ThrowsAsync<PostgresException>(() => command.ExecuteNonQueryAsync(ct));
        Assert.Equal(PostgresErrorCodes.InsufficientPrivilege, ex.SqlState);
    }

    /// <summary>
    /// The per-test schemas the key-store tests run in carry the same grant: a fixture that rendered
    /// 0002 without 0005 would run every adapter test against a key store no deployment has.
    /// </summary>
    [SuppressMessage(
        "Security",
        "CA2100:Review SQL queries for security vulnerabilities",
        Justification = "The interpolated schema name is generated by the fixture from a literal prefix and a GUID.")]
    [Fact]
    public async Task R4_32_TheIsolatedKeyStoreSchemasCarryTheSameGrant()
    {
        var ct = TestContext.Current.CancellationToken;
        var schema = await _fixture.CreateIsolatedOperationalSchemaAsync(ct);

        await using var connection = await _fixture.AppRoleDataSource.OpenConnectionAsync(ct);
        await using var command = new NpgsqlCommand(
            $"UPDATE \"{schema}\".agent_keys SET public_key = public_key WHERE kid = 'no-such-kid';", connection);

        var ex = await Assert.ThrowsAsync<PostgresException>(() => command.ExecuteNonQueryAsync(ct));
        Assert.Equal(PostgresErrorCodes.InsufficientPrivilege, ex.SqlState);
    }
}
