using System.Diagnostics.CodeAnalysis;
using Curia.Infrastructure.Migrations;
using Npgsql;
using Xunit;

namespace Curia.Infrastructure.Tests;

/// <summary>
/// Owns one throwaway Postgres database and one throwaway, R11.6-constrained application role
/// for the whole test run -- created in <see cref="InitializeAsync"/>, dropped in
/// <see cref="DisposeAsync"/>. Both names carry a random suffix so concurrent runs -- a
/// developer's machine and CI, or two CI jobs -- never collide, and dropping them here means a
/// run leaves nothing behind on the server it used.
///
/// Shared across every test class in this assembly via <see cref="PostgresCollectionDefinition"/>
/// rather than created per test class: CREATE DATABASE is not free, and every individual test
/// still gets a logically empty store through <see cref="ResetEventsTableAsync"/> (called from
/// each test class's own <c>CreateStore</c>), not through re-creating the database.
/// </summary>
[SuppressMessage(
    "Design",
    "CA1515:Consider making public types internal",
    Justification = "Constructor-injected into every [Fact]-bearing test class in this project via " +
        "ICollectionFixture<PostgresDatabaseFixture>; those classes must be public for xUnit to " +
        "discover them, and a public class cannot expose an internal type through a public " +
        "constructor parameter (CS0051), so this type is public by necessity, not by oversight.")]
public sealed class PostgresDatabaseFixture : IAsyncLifetime
{
    private string _maintenanceConnectionString = string.Empty;
    private string _databaseName = string.Empty;
    private string _roleName = string.Empty;
    private NpgsqlDataSource? _adminDataSource;
    private NpgsqlDataSource? _appRoleDataSource;

    /// <summary>Admin-privileged access to the throwaway database -- schema setup, TRUNCATE
    /// between tests, and anything else that needs more than INSERT/SELECT.</summary>
    public NpgsqlDataSource AdminDataSource => _adminDataSource
        ?? throw new InvalidOperationException($"{nameof(PostgresDatabaseFixture)} was not initialized.");

    /// <summary>
    /// Access to the throwaway database as the R11.6-constrained role -- the connection every
    /// <see cref="PostgresEventStore"/> under test in this project should be built against, so
    /// the whole contract suite runs under the real production privilege boundary, not merely
    /// the standalone grant-refusal test.
    /// </summary>
    public NpgsqlDataSource AppRoleDataSource => _appRoleDataSource
        ?? throw new InvalidOperationException($"{nameof(PostgresDatabaseFixture)} was not initialized.");

    [SuppressMessage(
        "Security",
        "CA2100:Review SQL queries for security vulnerabilities",
        Justification = "The only interpolated text is the result of QuoteIdentifier(_databaseName), " +
            "and _databaseName is generated by this same method (a literal prefix plus a GUID's hex " +
            "digits) two lines above, never external input.")]
    public async ValueTask InitializeAsync()
    {
        var adminConnectionString = PostgresTestEnvironment.ResolveAdminConnectionString();
        await PostgresTestEnvironment.EnsureReachableAsync(adminConnectionString, CancellationToken.None)
            .ConfigureAwait(false);

        var suffix = Guid.NewGuid().ToString("N")[..10];
        _databaseName = $"curia_test_{suffix}";
        _roleName = $"curia_app_test_{suffix}";
        var rolePassword = Guid.NewGuid().ToString("N");

        var maintenanceBuilder = new NpgsqlConnectionStringBuilder(adminConnectionString);
        _maintenanceConnectionString = maintenanceBuilder.ConnectionString;

        await using (var connection = new NpgsqlConnection(_maintenanceConnectionString))
        {
            await connection.OpenAsync().ConfigureAwait(false);
            await using var createDatabase = new NpgsqlCommand(
                $"CREATE DATABASE {QuoteIdentifier(_databaseName)};", connection);
            await createDatabase.ExecuteNonQueryAsync().ConfigureAwait(false);
        }

        var ephemeralBuilder = new NpgsqlConnectionStringBuilder(_maintenanceConnectionString)
        {
            Database = _databaseName,
        };

        var rendered = EventStoreSchema.Render(EventStoreSchema.LoadTemplate(), _roleName, rolePassword);
        await using (var connection = new NpgsqlConnection(ephemeralBuilder.ConnectionString))
        {
            await connection.OpenAsync().ConfigureAwait(false);
            await using var migrate = new NpgsqlCommand(rendered, connection);
            await migrate.ExecuteNonQueryAsync().ConfigureAwait(false);
        }

        _adminDataSource = NpgsqlDataSource.Create(ephemeralBuilder.ConnectionString);

        var appRoleBuilder = new NpgsqlConnectionStringBuilder(ephemeralBuilder.ConnectionString)
        {
            Username = _roleName,
            Password = rolePassword,
        };
        _appRoleDataSource = NpgsqlDataSource.Create(appRoleBuilder.ConnectionString);
    }

    /// <summary>
    /// Restores the store to logically empty between tests -- <see cref="EventStorePortContractTests"/>'s
    /// own contract for <c>CreateStore</c> ("a fresh, empty store... tests never see state
    /// another test left behind"). TRUNCATE, not per-test CREATE DATABASE: the events table is
    /// global (one IDENTITY sequence across every aggregate, per Appendix D), so an "empty
    /// store" for the contract suite's cross-aggregate read tests genuinely means an empty
    /// table, and TRUNCATE is orders of magnitude cheaper than a fresh database per test/
    /// per-property-iteration. Runs on <see cref="AdminDataSource"/>, not the app-role
    /// connection under test: TRUNCATE is exactly the elevated privilege R11.6 withholds from
    /// the application role, so this is test scaffolding resetting state, not the adapter
    /// exercising its own permissions.
    /// </summary>
    public async Task ResetEventsTableAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = await AdminDataSource.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await using var command = new NpgsqlCommand("TRUNCATE TABLE events RESTART IDENTITY;", connection);
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Provisions a brand-new Postgres schema containing its own <c>events</c> table and its
    /// own grant of INSERT/SELECT (and REVOKE of UPDATE/DELETE) to the fixture's throwaway
    /// application role, then returns the schema's name for <see cref="PostgresEventStore"/>'s
    /// <c>schema</c> constructor parameter.
    ///
    /// This exists because <c>EventStorePortContractTests</c>' <c>CreateStore</c> contract --
    /// "a fresh, empty store... once per generated case" -- turned out to need genuine
    /// per-call isolation, not merely sequential reset: CsCheck's property test runs its 200
    /// generated cases with real internal concurrency, so two cases' <c>CreateStore()</c>
    /// calls can be in flight at once. <see cref="ResetEventsTableAsync"/> (TRUNCATE on one
    /// shared table) is correct for sequential callers -- every xUnit [Fact] in this project's
    /// single collection, including every OTHER test class here -- but was falsified for
    /// CsCheck's concurrent ones: a minimal single-append case failed with a spurious
    /// curia/domain/concurrency-conflict because a concurrently running case's rows were
    /// visible on the shared table in between. A fresh schema per call is the fix: cheap
    /// (unlike a fresh throwaway database per call) and genuinely isolated (unlike a shared
    /// table), so <see cref="PostgresEventStoreContractTests.CreateStore"/> uses this instead
    /// of <see cref="ResetEventsTableAsync"/>.
    ///
    /// Schemas accumulate in the throwaway database for the run's duration rather than being
    /// dropped individually -- the whole database is dropped in <see cref="DisposeAsync"/>
    /// regardless, so an unused schema here is run-duration clutter inside a database that is
    /// about to disappear, not a leak.
    ///
    /// Known duplication, not an oversight: the <c>events</c> table columns below are a second
    /// copy of db/0001_create_events.sql's DDL rather than a re-render of that same template.
    /// The template also issues <c>CREATE ROLE</c>, which must run exactly once per role, not
    /// once per schema -- reusing it here would mean either re-templating it to skip the role
    /// statement (a second templating dimension for a test-only concern) or running a
    /// role-already-exists error path on every call. Re-typing seven column definitions was
    /// judged the smaller, more legible cost; <see cref="InitializeAsync"/> is what actually
    /// exercises the checked-in migration file byte-for-byte, which is what matters for
    /// verifying the real migration.
    /// </summary>
    [SuppressMessage(
        "Security",
        "CA2100:Review SQL queries for security vulnerabilities",
        Justification = "Every interpolated identifier is QuoteIdentifier applied to schemaName " +
            "(generated on the line above from a literal prefix plus a GUID's hex digits) or " +
            "_roleName (generated once in InitializeAsync the same way) -- never external input.")]
    public async Task<string> CreateIsolatedSchemaAsync(CancellationToken cancellationToken = default)
    {
        var schemaName = $"t{Guid.NewGuid():N}";
        var quotedSchema = QuoteIdentifier(schemaName);
        var quotedRole = QuoteIdentifier(_roleName);

        var sql = $"""
            CREATE SCHEMA {quotedSchema};
            CREATE TABLE {quotedSchema}.events (
              seq             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
              event_id        TEXT UNIQUE NOT NULL,
              event_type      TEXT NOT NULL,
              aggregate_id    TEXT NOT NULL,
              actor_id        TEXT,
              payload         JSONB NOT NULL,
              server_ts       TIMESTAMPTZ NOT NULL DEFAULT now()
            );
            GRANT USAGE ON SCHEMA {quotedSchema} TO {quotedRole};
            GRANT INSERT, SELECT ON {quotedSchema}.events TO {quotedRole};
            REVOKE UPDATE, DELETE ON {quotedSchema}.events FROM {quotedRole};
            """;

        await using var connection = await AdminDataSource.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);

        return schemaName;
    }

    [SuppressMessage(
        "Reliability",
        "CA1031:Do not catch general exception types",
        Justification = "Best-effort cleanup: this runs after the tests that matter have already " +
            "reported their own pass/fail, so a teardown failure (e.g. the server having vanished " +
            "mid-run) must not mask the real test outcome by throwing out of DisposeAsync.")]
    [SuppressMessage(
        "Security",
        "CA2100:Review SQL queries for security vulnerabilities",
        Justification = "The only interpolated text in either command below is QuoteIdentifier applied " +
            "to _databaseName/_roleName, both generated in InitializeAsync from a literal prefix plus a " +
            "GUID's hex digits, never external input.")]
    public async ValueTask DisposeAsync()
    {
        if (_appRoleDataSource is not null)
            await _appRoleDataSource.DisposeAsync().ConfigureAwait(false);
        if (_adminDataSource is not null)
            await _adminDataSource.DisposeAsync().ConfigureAwait(false);

        // Pooled connections to the throwaway database must be gone before DROP DATABASE, or
        // Postgres refuses it as "database is being accessed by other users" even with this
        // process's own pool as the only other user.
        NpgsqlConnection.ClearAllPools();

        if (string.IsNullOrEmpty(_maintenanceConnectionString))
            return; // InitializeAsync never got far enough to create anything.

        try
        {
            await using var connection = new NpgsqlConnection(_maintenanceConnectionString);
            await connection.OpenAsync().ConfigureAwait(false);

            if (!string.IsNullOrEmpty(_databaseName))
            {
                await using var dropDatabase = new NpgsqlCommand(
                    // WITH (FORCE), PG13+: terminates any lingering backend rather than failing
                    // the drop -- belt-and-braces alongside ClearAllPools above.
                    $"DROP DATABASE IF EXISTS {QuoteIdentifier(_databaseName)} WITH (FORCE);",
                    connection);
                await dropDatabase.ExecuteNonQueryAsync().ConfigureAwait(false);
            }

            if (!string.IsNullOrEmpty(_roleName))
            {
                // Only safe to drop AFTER the database is gone: a role that still holds
                // grants on live objects cannot be dropped, and dropping the database that
                // contained those objects is what clears them.
                await using var dropRole = new NpgsqlCommand(
                    $"DROP ROLE IF EXISTS {QuoteIdentifier(_roleName)};", connection);
                await dropRole.ExecuteNonQueryAsync().ConfigureAwait(false);
            }
        }
        catch (Exception)
        {
            // Best-effort: see the class-level SuppressMessage justification above. A future
            // run picks a fresh random suffix regardless, so a leaked throwaway database/role
            // from a failed teardown does not collide with anything; it is cluster clutter to
            // clean up by hand, not a correctness problem for the next run.
        }
    }

    /// <summary>
    /// Standard SQL identifier quoting (double quotes, embedded quotes doubled). Not
    /// <c>NpgsqlCommandBuilder.QuoteIdentifier</c> -- that member is an instance method on this
    /// Npgsql version, and constructing a whole <see cref="NpgsqlCommandBuilder"/> for one
    /// string operation would be a strange amount of ceremony for something this small.
    /// </summary>
    private static string QuoteIdentifier(string identifier) =>
        "\"" + identifier.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";
}
