<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Curia.Canon/Curia.Canon.csproj" />
    <ProjectReference Include="../../src/Curia.Canon.Sodium/Curia.Canon.Sodium.csproj" />
    <ProjectReference Include="../../src/Curia.Domain.Primitives/Curia.Domain.Primitives.csproj" />
    <ProjectReference Include="../../src/Curia.Domain/Curia.Domain.csproj" />
    <ProjectReference Include="../../src/Curia.Application/Curia.Application.csproj" />
    <ProjectReference Include="../../src/Curia.AuthN/Curia.AuthN.csproj" />
  </ItemGroup>
</Project>
